spring:
  application:
    name: nbapp
  
server:
  port: 8304

insbot:
  s3:
    cornSchedule: "*/5 * * * *"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
  instance:
      hostname: localhost
