spring:
  application:
    name: nbapp
  
server:
  port: 8304

insbot:
  s3:
    queueName: "EnrollmentFileQueue.fifo"
    queueUrl: "https://sqs.us-west-2.amazonaws.com/697233158446/EnrollmentFileQueue.fifo"
    cornSchedule: "* /1 * * * *"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
  instance:
      hostname: localhost
